name: 이슈 템플릿
description: 이슈를 생성할 때 사용하는 템플릿입니다.
title: ''
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🌈 Success criteria
        요구사항을 상세히 설명해주세요. 글/사진/그림(흐름도) 모두 사용해봅시다.
        예: 요구사항명세서를 참고해서 Main 시트의 메뉴 정보(전체)기능을 만들어주세요.

  - type: textarea
    id: success-criteria
    attributes:
      label: 요구사항 설명
      description: 구현해야 할 기능을 구체적으로 적어주세요.
    validations:
      required: true

  - type: textarea
    id: to-do
    attributes:
      label: 👷 To-do
      description: 구현을 위한 세부 단계를 체크리스트로 적어주세요.
      placeholder: |
        - [ ] 항목 1
        - [ ] 항목 2
        - [x] 완료 항목
    validations:
      required: false

  - type: textarea
    id: review
    attributes:
      label: 🧶 Review
      description: 작업 결과, 공유 내용, 스크린샷 등을 남겨주세요.
    validations:
      required: false
